### ISSUE TITLE
ImportError: libsixel not found.

### ISSUE THREAD

**Issue by happyprotean** [saitoha/libsixel#100]
Hi, sir. I "pip install libsixel-python" in  my anaconda environment and it shows libsixel-python is instlled. But when I import libsixel in code, an error arises: "ImportError: libsixel not found." What is the problem?
![image](https://user-images.githubusercontent.com/31753214/66636846-84b69400-ec44-11e9-8cbf-7c019b69b721.png)

**Comment by saitoha** [comment]
You have to install libsixel. libsixel-python is just a python binding for libsixel.
