### ISSUE TITLE
How to get libsixel / img2sixel for Windows? Can it be added to Windows package systems?

### ISSUE THREAD

**Issue by RioNight** [saitoha/libsixel#178]
How can I get libsixel / img2sixel for Windows? If there are no ready-made distributions, can it be added to the Windows package systems? I couldn't find it on scoop, winget, or choco.

Adding it to scoop might be the simplest.
https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests

**Comment by data-man** [comment]
Try asking here: https://github.com/libsixel/libsixel.

**Comment by GitMurf** [comment]
> Try asking here: https://github.com/libsixel/libsixel.

@data-man unfortunately that forked repository has also been abandoned it seems: https://github.com/libsixel/libsixel/discussions/76
