### ISSUE TITLE
http://sbo.syosetu.com/N9669BK/qrcode.png が正しく表示されない

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#22]
OS: Ubuntu 14.04.1 LTS (amd64)

```
$ wget -O - "http://sbo.syosetu.com/N9669BK/qrcode.png" | img2sixel
```

が正しく表示されなかったので、

```
$ wget -O - "http://sbo.syosetu.com/N9669BK/qrcode.png" | img2sixel | sixel2png >output.png
```

してみましたが、やはり正しく表示されませんでしたので確認をお願いできますでしょうか？

他に必要な情報がありましたら、お知らせください。

**Comment by msmhrt** [comment]
https://github.com/saitoha/libsixel/commit/cfc1ea16224d4fc7d143428a4fe3424cffa1ca4b までは問題がなく、 https://github.com/saitoha/libsixel/commit/ef44cffeb77daa21235456847451b030a83b389a で問題が発生しているようですので、恐らくはこの commit が原因ではないかと思われます。

**Comment by saitoha** [comment]
@msmhrt 再現しました。おそらくこうなってしまうということですよね。

![2015-02-01 20 00 29](https://cloud.githubusercontent.com/assets/1162739/5991860/0dc9e286-aa4d-11e4-88dd-b2f41a51e438.png)

**Comment by saitoha** [comment]
@msmhrt 原因がわかりました。
libpngを扱う際に、画像データのビット深度とパレットのビット深度を混同している処理がありました。
該当のpngでは画像データのビット深度=1、パレットのビット深度=8でした。
別々に扱うようにする修正を入れてv1.4.6を出します。

**Comment by msmhrt** [comment]
master の HEAD で問題なきことを確認しました。

ありがとうございました。m(__)m

**Comment by msmhrt** [comment]
すみません。今確認したら master の HEAD でも images/snake-monochrome.png が正しく表示できないようですので、確認していただけますでしょうか？
（別 Issue 立てたほうがいいでしょうか？）

**Comment by saitoha** [comment]
@msmhrt はい。 images/snake-monochrome.png はちょっとこちらで再現できないので、
別 Issue で状況を詳しく伺えればと思います。
