### ISSUE TITLE
GIF画像を表示すると多数のノイズが乗る

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#26]
OS: Ubuntu 14.04.1 (amd64)
Terminal: mlterm 最新版( https://bitbucket.org/arakiken/mlterm/commits/b2997e9c235db39ab79d3cf4c167c23796c0a5bb?at=default )

master ブランチの現在の HEAD ( https://github.com/saitoha/libsixel/commit/cdc6005baf76951e77ea926282d572fa5f2a678f ) でビルドした `img2sixel` で

![before](https://cloud.githubusercontent.com/assets/236546/6092354/ecc1bb24-af1d-11e4-967e-3e168ac73c57.gif)

( `before.gif` )を表示すると、

![after](https://cloud.githubusercontent.com/assets/236546/6092359/19435086-af1e-11e4-81c2-541f357f3cb5.png)

( `after.png` )のように表示され、多数のノイズが乗ってしまいます。

上の画像は透過GIF画像を `convert` コマンドで不透過にした物です。具体的には 

```
$ wget -O - "http://static.syosetu.com/view/images/syuppan_logo.gif?mvxta7" | convert -  \( +clone -alpha opaque -fill "#300824" -colorize 100% \) +swap -geometry +0+0 -compose Over -composite -alpha off before.gif
```

で作成しています。
下の画像は

```
$ img2sixel before.gif | sixel2png after.png
```

で作成していますので、端末側の問題ではないと思われます。

`img2sixel` の `-d` オプションで `fs` と `auto`  以外にした場合はノイズがありませんでしたので、特定のディザリング方式が影響しているのではないかと思われます。
（ついでで申し訳ないのですが、最大256色のGIF画像をディザリングしている理由がちょっと分からなかったので教えていただけないでしょうか？）

 `-I` オプションを追加した場合もノイズがありませんでした。

**Comment by saitoha** [comment]
これは、GIFの読み込み時に内部で一度RGB24bitのピクセルフォーマットに展開してしまっていたからです。
一度は8bitパレット形式で読んでこようとしてたんですが、GIFフォーマットにはアニメーションの各フレームごとに独立したパレットを持つことができる機能があり、全フレームを一気にもってくる現在の実装をベースにすると、256色パレットでもってこれる場合ともってこれない場合があります。
将来的に、1フレームづつコールバックで読んで処理する方法を採用することを考えているので、この修正はそのときに一緒にやりたいです。

**Comment by saitoha** [comment]
ディザリングが発生する理由はこれとは別でした。
ヒストグラムの作成の仕方がおかしかったことが影響しています。
32色の画像のはずなのに、737色を検出してしまっており、1行修正を入れたら直りました。
(./configure時に--enable-debugをつけると、色数が表示されるようになります)
hotfix-issue-26ブランチを試してみて下さい。

**Comment by saitoha** [comment]
あ、やっぱりまだ少しノイズが残りますね。

![2015-02-08 0 40 19](https://cloud.githubusercontent.com/assets/1162739/6092671/3afa02d0-af2b-11e4-878c-3b20d9f00b0d.png)

**Comment by msmhrt** [comment]
はい、同じ結果になりました。

**Comment by saitoha** [comment]
あーなるほど、実は、最適化のために各成分を3bit削って24bit -> 15bitとしているんですが(そうすると適用がかなり速くなる)、この時に生じた誤差が影響しています。
img2sixelに-vオプションをつけるとパレットの詳細を見ると、みんな2,4,6桁目が0か8にされてしまっているんですが、このパレットと実際のパレットの差が、誤差拡散でノイズ化します。
最適化をやめれば直るんですが、遅くなるのであまりやりたくないな、というジレンマがあります。

**Comment by saitoha** [comment]
元画像との誤差をとる時に、元画像側も各成分3bit切り落してみる、という修正案をhotfix-issue-26-candidate1ブランチに上げました。
でも階調が多めの画像では逆に誤差拡散が効きにくくなって、画質が悪化する恐れがあります。

**Comment by msmhrt** [comment]
なるほど、それならディザリング方式で結果が変わるのも納得ですね。

説明をうかがった限りではアニメーションGIF以外は24ビットフォーマット（正確には15ビットフォーマットでしょうか）に一度変換する必要はなさそうですので、将来的にその辺りの処理が追加されるまでは制限ということにして、いじらない方が良いのかもしれませんね。

**Comment by msmhrt** [comment]
現状でも他の誤差拡散形式を選択することで改善が見られる（その代わり処理が重くなる？）ようですので、改善するのが確実でしたら「ノイズが気になる場合は他の誤差拡散形式を選択していただければ処理は重くなりますがノイズが減ります」と案内しても構わないのかもしれません。

後は「元画像との誤差をとる時に、元画像側も各成分3bit切り落してみる」を `-d` オプションの（デフォルトではない）新しい選択肢として追加するくらいでしょうか。

**Comment by saitoha** [comment]
固定パレットを使わない設定時限定で、ヒストグラム作成時にカウントした色数(histogram_colors)が、要求した色数(reqcolors)より大きくなければ、ディザを無効にする(-d noneオプションの効果と同じ)、という修正をhotfix-issue-26-candidate2ブランチに入れてみました。

**Comment by msmhrt** [comment]
二点気になったので報告させてください。

1.  `issue-26-candidate2` ブランチの修正は `-d` オプションが `auto` だった場合に限定しなくても良いのでしょうか？　`-d` オプションで何を指定しても条件を満たせば `DIFFUSE_NONE` になるような気がしたのですが、私の勘違い、あるいは意図した仕様だったらすみません。

2. `issue-26-candidate*` ブランチは「任意の32色のGIF画像はそのまま出力できるので 32,768色画像に変換する処理は本来必要ないが、現在の `img2sixel` は全てのGIF画像を 32,768色画像に変換する仕様になっている。任意の32色のGIF画像を 32,768色画像に変換した場合に副作用が発生するので、それを低減する処理を追加した。」というのが私の理解なのですが、追加した処理が他の画像に与える悪影響が不安なので、「将来的に、1フレームづつコールバックで読んで処理する方法」が採用され、GIF画像のデコード結果に不要な処理を加えずに素直に出力できるようになる（んですよね？）まで（例の色数の検出のバグを除いて）修正しないという選択肢についても検討してみていただけないでしょうか？

**Comment by saitoha** [comment]
まず、1. については、autoに限定しなくてもいいと思います。
前提として、libsixelで行っているディザ処理は、-d none以外の何を指定しようと基本的にはパレット適用前と適用後の色の差分をとって、それをまわりのピクセルに拡散する、というものです。
また、固定パレット処理以外のケースで、かつ色数が減らない場合は理論上、全てのピクセルでパレット適用による色の変更が起こりません。
(あくまで理論上です。今はこれが起きてしまったので問題になっています)
よって、本来減色が起きないケースでは適用前と適用後の色の差分が0なので、それをまわりに拡散しようが何も起きず、`DIFFUSE_NONE`と結果は同じになります。
あと、無駄なことをやらなくなったので高速化しているはずです。
またノイズが乗らなくなるとsixelの圧縮が効きやすくなって、サイズが減少するメリットがあります。

**Comment by saitoha** [comment]
また、2.については、修正しないという選択肢についても検討してみます。
ただ、candidate2がうまくいっているようであれば、出力結果がきれいになるの+αのメリットがあるので現時点でも採用したいと思っています。

あと、24bit -> 15bit に切りつめているのは減色時に使うパレットが保持しているRGB値の方で、GIFのローダーが読んでくるピクセルフォーマットは24bitです。
なので「32,768色画像」の部分は、「24bit画像」という言い方が正しいです。

**Comment by msmhrt** [comment]
丁寧な説明ありがとうございました。

1. についてはユーザーがオプションで指定した処理方式が結果的に無視されることがあるのが気になったのですが、問題なかったようですね。

2. についてもメリットがいくつかあるので採用するということであればもっともなお話だと思います。

ただ説明をうかがっていて、よく似た色で2色の画像を黒白2色で出力するような場合も、色数は2色で変わらないという理由で誤差拡散処理が行われなくなるのだろうか？という点がちょっと気になりました。
それはまた別の話なので問題ないということでしたらすみません。

**Comment by saitoha** [comment]
今回candidate2で`DIFFUSE_NONE`相当の動きになるケースというのは、より正確に言うと

-I オプションでhigh color出力にならず、
-e オプションでモノクロ出力にならず、
-m オプションでユーザー定義パレットが適用されず、
-b オプションでビルトインパレットが適用されず、
ローダー側でパレット形式やグレースケール形式での読み込みができず、RGB24bitでピクセルデータをもってきた場合で、
かつ、ヒストグラムでカウントされた色数 <= 要求される色数 なケース

となります。
黒白2色で出力するケースというのは、-eか-mオプションを指定することになると思います。

これで100%確実に問題が起きないかと聞かれると大丈夫だと言い切る自信も無いので、これから色々な画像で試してみたいと思います。

**Comment by msmhrt** [comment]
詳細条件の説明ありがとうございました。しつこくお聞きしてすみませんでした。

こちらでも `issue-26-candidate2` ブランチを試していますので、もし何か見つかったら報告しますね。

**Comment by saitoha** [comment]
先日のコミット a465292 には実装上の問題があって、@msmhrt さんのご心配通り、画質にかなり影響がありました。
db4bd6a で修正しています。

**Comment by saitoha** [comment]
masterにマージしました。
