### ISSUE TITLE
develop ブランチで sixel2png コマンドが真っ黒な画像を出力する

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#30]
`develop` ブランチ（https://github.com/saitoha/libsixel/commit/ac4d2f3e60c0e98ec4c5ea8b93556d394b67a916 ) で

```
$ img2sixel images/snake.jpg | sixel2png >output.png
```

が元画像と同じサイズの真っ黒な画像を出力します。

`master` ブランチ（ https://github.com/saitoha/libsixel/commit/cdc6005baf76951e77ea926282d572fa5f2a678f ) と `hotfix-issue-29` ブランチ（ https://github.com/saitoha/libsixel/commit/b6748d1a49477200a7dfb93c767207d96aec53d5 ）では問題ありませんでした。

`img2sixel` の出力については `develop` ブランチ（https://github.com/saitoha/libsixel/commit/ac4d2f3e60c0e98ec4c5ea8b93556d394b67a916 ) と  `hotfix-issue-29` ブランチ（ https://github.com/saitoha/libsixel/commit/b6748d1a49477200a7dfb93c767207d96aec53d5 ）で同一であることを確認しています。

下記が実際に出力された画像です。
![output](https://cloud.githubusercontent.com/assets/236546/6205109/19a6a76a-b5a6-11e4-87a3-227aedc9df9c.png)

**Comment by saitoha** [comment]
すみません、実装途中状態のものをとりあえずコミットしたのを忘れてpushしてしまっていました。
ご報告ありがとうございます。

**Comment by saitoha** [comment]
`develop`にマージしました。
