### ISSUE TITLE
develop ブランチの img2sixel で libjpeg を使用すると JPEG ファイルでエラーが発生する

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#32]
【概要】
`develop` ブランチの `img2sixel` で libjpeg を使用すると JPEG ファイルでエラーが発生する

【発生環境】
OS: Ubuntu 14.04.2 LTS (amd64)
Terminal: mlterm version 3.4.3 post/2015-02-22

【詳細】
libjpeg を使用するようにビルドした `develop` ブランチ( https://github.com/saitoha/libsixel/commit/bf23ab67f59a660320c806b83f391155fc11d622 ) の `img2sixel` で JPEG ファイルを表示しようとすると、下記のエラーが表示される。

```
$ img2sixel images/egret.jpg
load_jpeg() failed(unknwon format).
Application transferred too few scanlines
$
```

`images/` 内の他の JPEG ファイルについても同じ結果です。

`master` ブランチ( https://github.com/saitoha/libsixel/commit/7efd9a4bb4f95d7842fe7cec3b9cf8f48f009804 ) でビルドした場合や `./configure` に `--without-jpeg` オプションを追加した場合は問題ありませんでした。

以下は使用した `libjpeg-dev` の詳細です。

```
$ apt-cache show libjpeg-dev
Package: libjpeg-dev
Priority: optional
Section: libdevel
Installed-Size: 26
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: libjpeg8-empty
Version: 8c-2ubuntu8
Depends: libjpeg8-dev
Filename: pool/main/libj/libjpeg8-empty/libjpeg-dev_8c-2ubuntu8_amd64.deb
Size: 1546
MD5sum: 48308774ecc38ee2cd8f9cf358c63ea4
SHA1: ab630ff891f59f96fba702c062f70a923f1b151e
SHA256: 5a676a4f0e5cf95124957e1935c2fdbae0841774b9760edbc49f5a438d153b16
Description-en: Independent JPEG Group's JPEG runtime library (dependency package)
 This package will always depend on the current default JPEG library
 development package version.
Description-md5: aeb3b35af5377dc1c08b3d3f1dd1de36
Multi-Arch: same
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m

$
```

**Comment by saitoha** [comment]
すみません。これもひどかったです...
3d6ca7d6 でエンバグしました。

**Comment by msmhrt** [comment]
`fix-issue-32` ブランチ( https://github.com/saitoha/libsixel/commit/d6ca032af6467b7cf15cb1895f5a2386626140e5 ) で上記の問題なきことを確認しました。

`develop` ブランチへのマージをよろしくお願いします。

**Comment by saitoha** [comment]
developにマージしました。
