### ISSUE TITLE
develop ブランチの img2sixel で -c オプションを使用すると画像が出力されない

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#33]
【概要】
`develop` ブランチの `img2sixel` で `-c` オプションを使用すると画像が出力されない

【発生環境】
OS: Ubuntu 14.04.2 LTS (amd64)
Terminal: mlterm version 3.4.3 post/2015-02-22

【詳細】
`develop` ブランチ( https://github.com/saitoha/libsixel/commit/bf23ab67f59a660320c806b83f391155fc11d622 ) の `img2sixel` で `-c` オプションを使用すると、下記のエラーが表示される。

```
$ img2sixel -c 600x450+0+0 images/snake.gif
usage: img2sixel [-78eIiugvSPDVH] [-p colors] [-m file] [-d diffusiontype]
                 [-f findtype] [-s selecttype] [-c geometory] [-w width]
                 [-h height] [-r resamplingtype] [-q quality] [-l loopmode]
                 [-t palettetype] [-n macronumber] [-C score] [-b palette]
                 [-E encodepolicy] [-B bgcolor] [filename ...]
for more details, type: 'img2sixel -H'.
$
```

`master` ブランチ( https://github.com/saitoha/libsixel/commit/7efd9a4bb4f95d7842fe7cec3b9cf8f48f009804 ) でビルドした場合は問題ありませんでした。

【その他】
`w3m` が `-c` オプションを使っているために画像が表示されないというのが、この Issue を見つけたきっかけでした。

**Comment by saitoha** [comment]
これはひどい...。
19417c65ad27b630916dfd39be9d96e68b1e1a9f でのエンバグです(境界条件の間違い)。

**Comment by msmhrt** [comment]
`fix-issue-33` ブランチ( https://github.com/saitoha/libsixel/commit/ff4db0b95f8be293f50c6a8b606e1e0d6c97c3a8 ) で上記の問題なきことを確認しました。

`develop` ブランチへのマージをよろしくお願いします。

**Comment by saitoha** [comment]
developにマージしました。
