### ISSUE TITLE
develop ブランチの img2sixel で -c オプションを使用すると一部のPNG画像が出力されない

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#38]
【概要】
`develop` ブランチの `img2sixel` で `-c` オプションを使用すると一部のPNG画像が出力されない

【発生環境】
OS: Ubuntu 14.04.2 LTS (amd64)
Terminal: mlterm version 3.4.3 post/2015-02-22
libpng: 1.2.50-1ubuntu2

【詳細】
`develop` ブランチ( https://github.com/saitoha/libsixel/commit/e953d9cd19f7e9416565ed7af12722133ab544fb ) で libpng を有効にして、下記のコマンドを実行すると画像が出力されません。

```
$  wget -O - "http://cdn-ak.favicon.st-hatena.com/?url=http%3A%2F%2Fheadlines.yahoo.co.jp%
2F" | img2sixel -c 16x16+0+0
```

`-c` オプション無しの場合や、libpng を無効にした場合、`master` ブランチ ( https://github.com/saitoha/libsixel/commit/7f7358573f7e4957dd483689782bfc3c127ceba6 ) にした場合は正常な画像が表示されました。

【その他】
画像は、はてブで表示される Yahoo!ニュースの favicon です。
https://github.com/saitoha/libsixel/issues/33 とは別問題のようですので別途 Issue を立てました。

**Comment by saitoha** [comment]
ご報告ありがとうございます。
これは`develop`で対応ピクセルフォーマットを増やしたことが影響しています。
増えた分に対応したクロップ処理がまだ実装されていない状況です。

**Comment by msmhrt** [comment]
現時点では未実装ということですね。了解です。

"not implemented yet" みたいなタグがあると良いのかもしれませんね。

既知の制限に返信のお手数をおかけしてすみませんが、報告しないで漏れるのも怖いのでどうかよろしくお願いします。

**Comment by saitoha** [comment]
`develop`にマージしました。

**Comment by msmhrt** [comment]
`develop` ブランチ( https://github.com/saitoha/libsixel/commit/662c66c3659acb21b31bc67e2c272c3c9379b0d0 ) で問題なきことを確認しました。

念のため `master` ブランチ( https://github.com/saitoha/libsixel/commit/a70ae723a529cd19e0db67a9f05bb5d90946f3d1 ) でも確認しましたが問題ありませんでした。

**Comment by saitoha** [comment]
ご確認ありがとうございます！
