### ISSUE TITLE
Last parameter of load_pnm has pointer vs. non-pointer conflict

### ISSUE THREAD

**Issue by tautschnig** [saitoha/libsixel#40]
Hello,

While compiling libsixel using our tool chain we noticed that the last parameter of load_pnm has inconsistent declarations:

https://github.com/saitoha/libsixel/blob/master/converters/frompnm.h#L37
vs.
https://github.com/saitoha/libsixel/blob/master/converters/frompnm.c#L58

It seems that (luckily) this parameter isn't being used at present, but whenever it is, this will severe security implications.

Best,
Michael

**Comment by saitoha** [comment]
@tautschnig Thanks! This fix will be included in the v1.4.10 release of libsixel.

**Comment by saitoha** [comment]
Merged. Thanks!
