### ISSUE TITLE
img2sixel で http://static.syosetu.com/view/images/liteaward2_a.gif が黒画像で表示される

### ISSUE THREAD

**Issue by msmhrt** [saitoha/libsixel#41]
【概要】
`img2sixel` で http://static.syosetu.com/view/images/liteaward2_a.gif が黒画像で表示される

【発生環境】
OS: Ubuntu 14.04.2 LTS (amd64)
Terminal: mlterm version 3.4.5 post/2015-03-24

【詳細】
master ブランチ( https://github.com/saitoha/libsixel/commit/a70ae723a529cd19e0db67a9f05bb5d90946f3d1 ) で http://static.syosetu.com/view/images/liteaward2_a.gif を表示すると黒画像で表示されてしまいます。

develop ブランチ( https://github.com/saitoha/libsixel/commit/662c66c3659acb21b31bc67e2c272c3c9379b0d0 ) では問題ありませんでした。

**Comment by saitoha** [comment]
stb_image 1.4系の既バグのようです。
画像全体のグローバルパレットではなく、フレームごとのローカルパレットを使った時に顕在化するバグで、結構影響範囲大きかったんじゃないかと思います。
本家ではこのコミットでしれっと修正されていました。
https://github.com/nothings/stb/commit/49d4d3193f54525b177d75d62560c6cf4b7302a7

**Comment by msmhrt** [comment]
`hotfix-issue-41` ブランチ( https://github.com/saitoha/libsixel/commit/1b30ea5ad0019ea660f1f50fdfcca82b50255745 ) で問題なきことを確認しました。

**Comment by saitoha** [comment]
`master`にマージしました。
