### ISSUE TITLE
img2sixelでgdk-pixbufを使用すると正しく変換されない画像がある。

### ISSUE THREAD

**Issue by ttdoda** [saitoha/libsixel#43]
libsixelを --with-gdk-pixbuf2 でビルドした時、正しく変換されない画像があります。

例1: https://pbs.twimg.com/media/CGLouJVUIAEMLFr.jpg
  斜めにずれる。

例2: https://pbs.twimg.com/media/CGpSB-0UIAACb1d.jpg:large
  斜めにずれる他、色もおかしい。

1.4.11、およびdevelopブランチの両方で問題がでます。
使用しているgdk-pixbuf のバージョンは 2.31.2 です。

**Comment by saitoha** [comment]
@ttdoda ちょっとまだ変更箇所全てを通るテストができていませんが、`hotfix-issue-43`ブランチと、`develop`ブランチの両方で直したつもりです。

**Comment by ttdoda** [comment]
ありがとうございます。sayakaでtwitterのタイムラインをしばらく流しっぱなしにして試してみましたが、
1.4.11で問題が出る画像すべてが hotfix-issue43ブランチ、およびdevelopブランチ共に問題なく表示できました。

**Comment by saitoha** [comment]
`master`にマージしました。
