### ISSUE TITLE
Providing an updated 256bit color patch for xterm

### ISSUE THREAD

**Issue by ismail** [saitoha/libsixel#47]
https://gist.github.com/saitoha/7822989 no longer applies to recent xterm versions. Would it be possible to update the patch?

**Comment by saitoha** [comment]
@ismail That patch seems to be no longer needed now. Try

```sh
$ echo "XTerm*decTerminalID: vt340" >> $HOME/.Xresources
$ echo "XTerm*numColorRegisters: 256" >>  $HOME/.Xresources
$ xrdb $HOME/.Xresources 
$ xterm
```

or

```sh
$ xterm -xrm "XTerm*decTerminalID: vt340" -xrm "XTerm*numColorRegisters: 256" 
```

**Comment by ismail** [comment]
Indeed you are right! Would be nice to document this :-) Thanks a lot!
