### ISSUE TITLE
Build fails on cygwin

### ISSUE THREAD

**Issue by mintty** [saitoha/libsixel#49]
...
checking for GNU libc compatible realloc... no
checking for memset... no
configure: error: memset is not available.

**Comment by saitoha** [comment]
@mintty Can you send me your config.log?
Here is my config.log on my i686 cygwin environment.
[config.log.txt](https://github.com/saitoha/libsixel/files/385323/config.log.txt)

**Comment by mintty** [comment]
[config.log.txt](https://github.com/saitoha/libsixel/files/388271/config.log.txt)

**Comment by k-takata** [comment]
> /bin/ld: cannot open output file conftest.exe: Permission denied
> collect2: error: ld returned 1 exit status

Something wrong in your directory permission?
Build succeeded on my x86_64 cygwin environment.

**Comment by saitoha** [comment]
@mintty I found similar issue here.
https://cygwin.com/ml/cygwin/2015-08/msg00433.html

**Comment by mintty** [comment]
Yes, thanks for the hint. I could have simply retried myself, sorry.
