### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [saitoha/libsixel#5]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [ftell](http://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "return a file offset") ⇒ [stbi_info_from_file](https://github.com/saitoha/libsixel/blob/f405013629cf28ca636e716be79bafab3bdeee09/converters/stb_image.h#L4571)
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "binary output") ⇒ [sixel_to_png](https://github.com/saitoha/libsixel/blob/cf6b1c58f7505dec57de0f901bf23b67f5a4e316/converters/sixel2png.c#L78)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "memory allocation") ⇒ [sixel_create_image](https://github.com/saitoha/libsixel/blob/a6d1abe788f94df3c2a8fdd5fb3d3c6fedf5bd1d/src/image.c#L31)

**Comment by saitoha** [comment]
I think it's done in `develop` branch.
Semantic error handling is available by introducing new API set that returns error code `SIXELSTATUS`.
Thanks!

**Comment by elfring** [comment]
Did you try any static source code analysis out with your updated application programming interface?

How do you think about to annotate any functions with "[`__attribute__((warn_unused_result))`](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Function-Attributes.html#index-g_t_0040code_007bwarn_005funused_005fresult_007d-function-attribute-3299 "Warn on unused results?")"?
