### ISSUE TITLE
--enable-sixel-graphics

### ISSUE THREAD

**Issue by nilqed** [saitoha/libsixel#51]
Today I got the following reply:
 
>> with --enable-sixel-graphics (configure).
> 
> Oops, I compiled xterm with "--enable-sixel", which is what
> https://github.com/saitoha/libsixel said.
> 
> Now I compile it with "--enable-sixel-graphics" and it works.
> 
> I guess you should open an issue for https://github.com/saitoha/libsixel .
> 

BTW terrific thing!  Thank you.

**Comment by saitoha** [comment]
Thanks!

**Comment by nilqed** [comment]
Not at all! I have to thank YOU.
This link https://groups.google.com/forum/#!topic/fricas-devel/GJfUAyH2S2I
will show the history of the "discovery" ;)

One oddity I further noticed in xterm was that the (default?) "jump
scrolling" may tear the graphics apart. After having disabled jump
scrolling by "xterm +j -ti vt340" the effect didn't show up anymore. This
problem, however, never occurred when using mlterm or mintty.

Best regards
Kurt

**Comment by saitoha** [comment]
@nilqed Thanks for letting me know!
Furthermore I found such nice thing:
https://github.com/nilqed/sixelSPAD
I'll try it.

>  "jump scrolling" may tear the graphics apart. After having disabled jump scrolling" may tear the graphics apart.

Hmm... I can't reproduce it in my environment (OSX 10.11 + Xquartz + Xterm#325).

**Comment by nilqed** [comment]
Am 12.10.2016 um 19:01 schrieb Hayaki Saito:
> @nilqed Thanks for letting me know!
> Furthermore I found such nice thing:
> https://github.com/nilqed/sixelSPAD
> I'll try it.
> 

I just started it, so it's a project in progress (actually everything perfectly
works and I only have to collect it in github). Your work on sixel is really
awesome and I now can realize of what I dreamt for a long time.

>>  "jump scrolling" may tear the graphics apart. After having disabled jump scrolling" may tear the graphics apart.
> 
> Hmm... I can't reproduce it in my environment (OSX 10.11 + Xquartz + Xterm#325).
All the better! I'm using Ubuntu and the +j option was helpful. On the other
hand there may be other causes. Anyway I wanted to let you know just in case
someone will complain.
>
