### ISSUE TITLE
Out of tree builds not working

### ISSUE THREAD

**Issue by tkelman** [saitoha/libsixel#56]
I usually like to run configure and make from a subfolder, e.g.
`mkdir build && cd build && ../configure && make`
to keep the source and the build products separate (aka VPATH build).

I'm trying this in cygwin 64 bit at the moment, and it isn't working correctly. On Ubuntu 14.04 I see similar behavior.

gist of output from running `../configure` https://gist.github.com/1fd5a01c747c95e564e1d258cc237440
gist of `config.log` and `Makefile` from `build` after running `../configure` https://gist.github.com/9bb454cad03df4759b1d627851b07661

My autotools is a little rusty so nothing jumps out at me to fix this. Any ideas?

**Comment by saitoha** [comment]
Fixed on v1.8.6. Thanks!
