### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [saitoha/libsixel#6]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [prepare_specified_palette](https://github.com/saitoha/libsixel/blob/fdc1aa19cd6a3ca192eda95239568a4a56f99d84/converters/img2sixel.c#L120)
* [sixel_dither_destroy](https://github.com/saitoha/libsixel/blob/216e61b4e3f95d952b881b12c30ba379b2cb706b/src/dither.c#L153)
* [sixel_image_destroy](https://github.com/saitoha/libsixel/blob/cf6b1c58f7505dec57de0f901bf23b67f5a4e316/src/image.c#L49)

Would you like to add the following semantic patch approach to a test directory?
```
@Remove_unnecessary_pointer_checks1@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);

@Remove_unnecessary_pointer_checks2@
expression x;
@@
-if (\(x != 0 \| x != NULL\)) {
    free(x);
    x = \(0 \| NULL\);
-}

@Remove_unnecessary_pointer_checks3@
expression a, b;
@@
-if (\(a != 0 \| a != NULL\) && \(b != 0 \| b != NULL\))
+if (a)
    free(b);

@Remove_unnecessary_pointer_checks4@
expression a, b;
@@
-if (\(a != 0 \| a != NULL\) && \(b != 0 \| b != NULL\)) {
+if (a) {
    free(b);
    b = \(0 \| NULL\);
 }
```

How do you think about to apply a corresponding update suggestion which will eventually be generated by [the software "Coccinelle"](http://coccinelle.lip6.fr/ "Source code transformation engine")?

**Comment by saitoha** [comment]
fixed.
