### ISSUE TITLE
Poor quality

### ISSUE THREAD

**Issue by GasparVardanyan** [saitoha/libsixel#86]
https://i.imgur.com/B5HXWNO.png

**Comment by saitoha** [comment]
Try:
$ echo "XTerm*numColorRegisters: 256" >>  $HOME/.Xresources
$ xrdb $HOME/.Xresources
$ xterm

**Comment by GasparVardanyan** [comment]
It helps, but sixcat, which uses sixel graphics, works better. And when the width is more than 1000, img2sixel does not work.
https://i.imgur.com/wIcdPQu.png
https://gist.github.com/hackerb9/a96cea91e6122d09a6c97f5eb797d5fa

**Comment by saitoha** [comment]
try:
```
XTerm*maxGraphicSize: 1980x1440
```

**Comment by GasparVardanyan** [comment]
Poor quality https://i.imgur.com/owx3po8.png

**Comment by GasparVardanyan** [comment]
But sometimes works fine https://i.imgur.com/4VzrhYd.png

**Comment by saitoha** [comment]
To check the number of color registers, type:
```
$ printf "\033[?1;1;S";cat
```

**Comment by GasparVardanyan** [comment]
https://i.imgur.com/5cexpLB.png
