### ISSUE TITLE
Question: VNC with sixel support?

### ISSUE THREAD

**Issue by cosmos72** [saitoha/libsixel#87]
Hello,
I am starting to experiment with libsixel, and I am looking for graphical servers that can use libsixel as rendering engine.
I see that Xsixel is a (hopefully) complete X11 server using libsixel, and I was wondering:

Is there a VNC client (or even an RDP client) that uses libsixel for rendering?

A quick google search did not return anything...

**Comment by saitoha** [comment]
As far as I know it does not exist.
